org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=34
# ★ release 签名密钥（app/release.keystore，alias=adpurge）
RELEASE_STORE_PASSWORD=AdpurgeVArZ6MqTW942mLhaA1!
RELEASE_KEY_PASSWORD=AdpurgeVArZ6MqTW942mLhaA1!
